### ISSUE TITLE
Docker compose failing when building

### ISSUE THREAD

**Issue by mr-grj** [artiz/beobachter#16]
This seems like a nice project but there are some issues with it. 

After cloning the project: `git clone https://github.com/artiz/beobachter.git` and going to the project directory, I tried running: ` docker-compose -f docker-compose.yml up --build`.

These are the issues that I can see:

Backend:

```
beo_backend            | bash: app/run.sh: No such file or directory
beo_backend exited with code 127
```

Nginx:

```
fast_treat-nginx-1     | 2023/01/11 14:40:15 [emerg] 1#1: host not found in upstream "backend:8888" in /etc/nginx/conf.d/default.conf:11
fast_treat-nginx-1     | nginx: [emerg] host not found in upstream "backend:8888" in /etc/nginx/conf.d/default.conf:11
```

Celery worker:

```
fast_treat-worker-1    | Usage: celery [OPTIONS] COMMAND [ARGS]...
fast_treat-worker-1    | Try 'celery --help' for help.
fast_treat-worker-1    | 
fast_treat-worker-1    | Error: Invalid value for '-A' / '--app': 
fast_treat-worker-1    | Unable to load celery application.
fast_treat-worker-1    | While trying to load the module app.tasks the following error occurred:
fast_treat-worker-1    | Traceback (most recent call last):
fast_treat-worker-1    |   File "/usr/local/lib/python3.10/site-packages/celery/bin/celery.py", line 53, in convert
fast_treat-worker-1    |     return find_app(value)
fast_treat-worker-1    |   File "/usr/local/lib/python3.10/site-packages/celery/app/utils.py", line 384, in find_app
fast_treat-worker-1    |     sym = symbol_by_name(app, imp=imp)
fast_treat-worker-1    |   File "/usr/local/lib/python3.10/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
fast_treat-worker-1    |     module = imp(module_name, package=package, **kwargs)
fast_treat-worker-1    |   File "/usr/local/lib/python3.10/site-packages/celery/utils/imports.py", line 100, in import_from_cwd
fast_treat-worker-1    |     return imp(module, package=package)
fast_treat-worker-1    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
fast_treat-worker-1    |     return _bootstrap._gcd_import(name[level:], package, level)
fast_treat-worker-1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
fast_treat-worker-1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
fast_treat-worker-1    |   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
fast_treat-worker-1    | ModuleNotFoundError: No module named 'app'
```

Frontend:

```
beo_frontend           | ERROR in src/components/dropdown/Menu.tsx:83:17
beo_frontend           | TS2345: Argument of type '{ toggle: boolean; pointerDown: boolean; ignoreMouse: boolean; }' is not assignable to parameter of type 'Props'.
beo_frontend           |   Object literal may only specify known properties, and 'pointerDown' does not exist in type 'Props'.
beo_frontend           |     81 |             useClick(context, {
beo_frontend           |     82 |                 toggle: !nested,
beo_frontend           |   > 83 |                 pointerDown: true,
beo_frontend           |        |                 ^^^^^^^^^^^^^^^^^
beo_frontend           |     84 |                 ignoreMouse: nested,
beo_frontend           |     85 |             }),
beo_frontend           |     86 |             useRole(context, { role: "menu" }),
beo_frontend           | 
beo_frontend           | ERROR in src/components/dropdown/Menu.tsx:204:29
beo_frontend           | TS2322: Type '{ children: Element; context: FloatingContext<HTMLButtonElement>; preventTabbing: true; modal: boolean; order: ("content" | "reference")[]; }' is not assignable to type 'IntrinsicAttributes & Props<HTMLButtonElement>'.
beo_frontend           |   Property 'preventTabbing' does not exist on type 'IntrinsicAttributes & Props<HTMLButtonElement>'.
beo_frontend           |     202 |                         <FloatingFocusManager
beo_frontend           |     203 |                             context={context}
beo_frontend           |   > 204 |                             preventTabbing
beo_frontend           |         |                             ^^^^^^^^^^^^^^
beo_frontend           |     205 |                             modal={!nested}
beo_frontend           |     206 |                             // Touch-based screen readers will be able to navigate back to the
beo_frontend           |     207 |                             // reference and click it to dismiss the menu without clicking an item.
beo_frontend           | 
beo_frontend           | ERROR in src/core/api/client.ts:74:9
beo_frontend           | TS2322: Type 'T' is not assignable to type 'T & { detail?: string | undefined; }'.
beo_frontend           |   Type 'T' is not assignable to type '{ detail?: string | undefined; }'.
beo_frontend           |     72 |         super();
beo_frontend           |     73 |
beo_frontend           |   > 74 |         this.data = d;
beo_frontend           |        |         ^^^^^^^^^
beo_frontend           |     75 |     }
beo_frontend           |     76 | }
beo_frontend           |     77 |
beo_frontend           | 
beo_frontend           | ERROR in src/core/api/client.ts:204:13
beo_frontend           | TS2322: Type 'T' is not assignable to type 'T & { detail?: string | undefined; }'.
beo_frontend           |   Type 'T' is not assignable to type '{ detail?: string | undefined; }'.
beo_frontend           |     202 |
beo_frontend           |     203 |         if (result?.headers?.get("content-type")?.includes("json")) {
beo_frontend           |   > 204 |             result.data = (await result.json()) as T;
beo_frontend           |         |             ^^^^^^^^^^^
beo_frontend           |     205 |         }
beo_frontend           |     206 |
beo_frontend           |     207 |         let ex: Error | undefined;
```

**Comment by artiz** [comment]
OK, will check it

**Comment by artiz** [comment]
I am using WSL2 under Windows 11 on my workstation, just run proejcvt build from scratch and all images were build correctly, could you check  docker/docker-compose version on your side? Docker-compose v2 required
I have following:
```
➜  docker -v
Docker version 20.10.21, build baeda1f
➜  docker-compose -v
Docker Compose version v2.13.0
```

**Comment by artiz** [comment]
Just fixed frontend build, please check latest master.
Concerning backend - please run backend Docker image build to get error details:
``` docker build backend --progress=plain --no-cache```

**Comment by artiz** [comment]
@alexandru-grajdeanu any news?
